HACKATHON_TITLE = "GPT-4 Powered App Creation and Evals Hackathon"
PERSIST_DIR = "./base_index_openai"
SOP_DATA_PATH = "./data/sop_chat_logs_duo_article_data/"
IMAGE_PATH = "/data/images/"
CHAT_DATA_PATH = "./data/chat_data/chat_data.json"
DESCRIPTION_QUESTION =  "Give me 10 words description of the conversation provided"
WELCOME_MESSAGE = "Hi there, this is SolvIT! How can I assist with your IT needs today?"
DEFAULT_USER_QUERY = "Getting this error."
REINDEX = False